Repository aditya109/git-osp-for-beginners, pull requests merged in 2020-10, with the labels that each got.

#13 Created DisplayPrimeArrayElements.java
  Programming/Java/Problem1/DisplayPrimeArrayElements.java
Labels: Great Work !, good first issue

#16 (Refactor) : removed Applications
  Applications/CRUDRestAPI/Java/pom.xml
Labels: bug

#20 added by second program DisplayHighestRunsScored.java
  Programming/Java/Problem2/DisplayHighestRunsScored.java
Labels: Great Work !

#7 Added Code for c++
  Programming/C++/Problem1/DisplayPrimeArrayElements.cpp
Labels: Great Work !

#12 20 Prime Numbers
  Programming/Python/Problem1/DisplayPrimeArrayElements.py
Labels: Great Work !, Hacktoberfest, good first issue

#9 add DisplayPrimeArray in golang
  Programming/Golang/Problem1/DisplayPrimeArrayElements.go
Labels: Great Work !, Hacktoberfest, good first issue

#22 Create CountingTheWordsStartingWithVowels.java
  Programming/Java/Problem3/CountingTheWordsStartingWithVowels.java
Labels: Great Work !, Hacktoberfest, good first issue, hacktoberfest-accepted

#30 Created CountWordsStartingwithaVowel.py
  Programming/Python/Problem2/CountWordsStartingwithaVowel.py
Labels: Great Work !, Hacktoberfest

#29 Python Patterns
  Programming/Python/Problem1/Patterns/Pattern1.py
  Programming/Python/Problem1/Patterns/Pattern2.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#38 Follow steps for contribute
  README.md
Labels: Great Work !, documentation, hacktoberfest-accepted

#42 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/programming-question.md
Labels: Hacktoberfest, good first issue, hacktoberfest-accepted

#33 Solved highest scorer problem in C++
  Programming/C++/Problem3/HighestScorer.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#82 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#17 Added Golang DisplayPrimeArrayElements
  Programming/Golang/Problem1/DisplayPrimeArrayElements.go
  Programming/Golang/Problem1/DisplayPrimeArrayElementsInput.go
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#103 Create PassOrFail.java
  Programming/Java/PassOrFail/PassOrFail.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#31 Added python program to count words starting with vowels
  Programming/_Python/Counting_words_starting_with_vowels.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#37 added file CountDigits
  Programming/Java/Problem4/CountDigits.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#96 Optimized the code.
  Programming/Java/Problem1/DisplayPrimeArrayElements.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#41 Tower Of Hanoi
  Programming/C++/Problem2/TowerOfHanoi
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#43 Added Grading Students Algorithm in (Python)
  Programming/Python/GradingStudents/gradingStudents.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#44 Create IsYourPasswordStrong.py
  Programming/Python/IsYourPasswordStrong/IsYourPasswordStrong.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#141 Update DisplayHighestRunsScored.java ( Fixed input and player name bug)
  Programming/Java/Problem2/DisplayHighestRunsScored.java
Labels: Great Work !, bug, hacktoberfest-accepted

#70 Update DisplayPrimeArrayElements.py
  Programming/Python/Problem1/DisplayPrimeArrayElements.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#68 Update DisplayPrimeArrayElements.java
  Programming/Java/Problem1/DisplayPrimeArrayElements.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#57 Words Starting With Vowels
  Programming/C++/Problem2/wordsStartingWithVowels.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#59 Added Tower of Hanoi
  Programming/Java/Problem4/TowerOfHanoi.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#62 Create fahrenheit to degree celsius
  fahrenheit to degree celsius
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#63 Python program to solve quadric equations
  QuadraticEquationSolver.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#64 Added canny edge detection python program
  CannyEdgeDetection.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#54 Solved Roots of Quadratic Equation and Prime Number upto N in python
  Programming/Python/PrimeNumbersUptoN/PrimeNumbersUptoN.py
  Programming/Python/RootsOfQuadraticEquation/RootsOfQuadraticEquation.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#52 Create hotelmanagementsystem.cpp
  Programming/C++/hotelmanagementsystem.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#106 Tower of Hanoi in Java using recursion
  Programming/Java/TowerOfHanoi/tower_of_hanoi.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#105 Fibonacci-Seq-Added
  Programming/Java/Problem5/fibonacciSeq.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#65 Python program for bilateral filtering
  BilateralFiltering.ipynb
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#107 Tower Of Hanoi code using recursion in C++
  Programming/C++/TowerOfHanoi/tower_Of_Hanoi.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#109 ⚡️ Added new Python and Java solutions
  Programming/Java/Problem5/PalinPairs.java
  Programming/Java/Problem6/tree_problem_1.java
  Programming/Python/Problem2/matrix_mean.py
  Programming/Python/Problem4/matrix_product.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#118 JS bubblesort
  Programming/JavaScript/Bubblesort/bubblesort.js
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#113 added balance string problem
  Programming/C++/isPrime/balancestrings.cpp
  Programming/C++/isPrime/isPrime.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#112 Add a new algorithm example for Palindrome
  Programming/Java/Palindrome/Palindrome.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#98 added more conditions to make the program precise
  Programming/C++/Problem1/DisplayPrimeArrayElements.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#69 Update HighestScoringPlayer.py
  Programming/Python/Problem3/HighestScoringPlayer.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#74 Created file for highest scorer
  Programming/C++/Problem4/highest_scorer.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#92 Program to print Hello World in Java using Custom Class instead of System Class
  Programming/Java/HelloWorld_CustomClassName/AkDemo.class
  Programming/Java/HelloWorld_CustomClassName/AkDemo.java
  Programming/Java/HelloWorld_CustomClassName/Akshat.class
  Programming/Java/HelloWorld_CustomClassName/Akshat.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#79 added the converting celsius to farenheiht program in java
  Programming/Java/Problem4/ConvertCelsiusIntoFahrenheit.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#88 Added count digits program in Java
  Programming/Java/Count Digits in O(1)/countDigits.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#94 String Palindrome and Reverse Number Program added
  Programming/Java/Problem4/ReverseNumber.java
  Programming/Java/Problem4/StringPalindrome.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#90 2 Strings anagram or not
  Programming/Java/Problem4/TwoStringsAnagrams.java
  Programming/Java/Problem5/CountDigits.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#87 add count the words starting with vowels
  Programming/C++/Problem2/CountTheWordsStartingWithVowels.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#111 Added new star pattern using Python.
  Programming/Python/Problem1/Patterns/Pattern3.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#71 Added ValidAnagram.cpp #58
  Programming/C++/Problem4/ValidAnagram.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#85 done anagram or not
  Programming/Java/Problem4/AnagramOrNot.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#84 Convert Celsius to Fahrenheit added - PR
  Programming/Java/Problem4/CelciusToFahrenheit.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#81 Convert Celcius to Fahrenheit | Java
  Programming/Java/Problem4/ConvertCelciusToFahrenheit.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#80 Count the number of digits in an integer
  Programming/Java/Problem4/CountDigits
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#77 Checking the number is prime or not
  Programming/C++/Problem4/CheckthenumberisPrimeOrNot.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#138 Strong Password (Java)
  Programming/Java/Problem6/Strong Password
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#130 PasswordChecker
  Programming/C++/PassStrengthChecker/check_pass_strength.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#132 Code for Counting Number of Words beginning with Vowels in Golang
  Programming/Golang/Problem 3/main.go
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#120 Sorted linked list
  Programming/C++/sortedLinkedList.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#119 Added 2 Programs PalindromeOrNot and AnagramsOrNot
  Programming/Java/AnagramsOrNot/AnagramsOrNot.java
  Programming/Java/PalindromeOrNot/PalindromeOrNot.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#143 Add files via upload
  activity_selection_problem.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#146 Create count vowels.cs
  Programming/C# sharp/count vowels.cs
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#86 CELCIUS2FARENHEIT Done
  Programming/Java/Problem4/CelciusToFarenheit.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#100 added porcupine.java problem
  Programming/Java/Problem4/Porcupine.java
  Programming/Java/Problem5/FibonacciSeries.java
  Programming/Java/Problem6/iterator.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#117 Two strings are anagrams or not
  Programming/Java/Problem5/Two strings are anagrams or not
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#114 String Anagrams
  Programming/Java/isAnagram/IsAnagram.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#95 Two Strings are Anagrams or not Solution in JAVA.
  s3.txt
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#149 Update DisplayPrimeArrayElements.java
  Programming/Java/Problem1/DisplayPrimeArrayElements.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#148 added various programs
  Programming/C++/Circular Linked List/Circular_Link_List.cpp
  Programming/C++/Posssible Sum/Possible_sum.cpp
  Programming/C++/Singly Linked List/linkedlist.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#158 Update README.md
  README.md
Labels: Hacktoberfest, documentation, hacktoberfest-accepted

#170 Update README.md
  README.md
Labels: Great Work !, Hacktoberfest, documentation, hacktoberfest-accepted

#156 Added Anagram Unique Approach for Issue #83
  Programming/Java/AnagramUnique(by xyther14)/Anagram.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#160 Create checkStrongPassword.java Resolves #126
  Programming/Java/IsYourPasswordStrong/checkStrongPassword.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#167 Added a file StrongPsswd
  Programming/Java/CheckPsswdStrongOrNot/StrongPsswd.java
Labels: Great Work !, Hacktoberfest, changes-requested, hacktoberfest-accepted

#168 Count digit
  Programming/Java/CountDigit O(1)/CountDigit.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#169 Fibonacci Sequence in c++
  Programming/C++/Fibonacci/Fibonacci.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#171 added n queen problem and solution with java
  Programming/Java/NQueen_Problem/NQueen_Problem and Explanation.md
  Programming/Java/NQueen_Problem/NQueen_Problem.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#172 added checkPrime in java
  Programming/Java/CheckPrime/checkPrime.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#173 Create greaterBranch.js
  Programming/JavaScript/Binary-Trees/greaterBranch.js
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#174 Create mergeSort.js
  Programming/JavaScript/Merge-Sort/mergeSort.js
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#175 Create permutations.js
  Programming/JavaScript/Algorithm/permutations.js
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#176 Create KLargestElements.java
  Programming/Java/KLargestElements/KLargestElements.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#181 Luhns algorithm in Python
  Programming/Python/LuhnAlgorithm/luhn_algorithm.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#177 Added the Luhn's Algorithm
  Programming/Java/Luhn'sAlgorithm/LuhnsAlgo.java
  Programming/Java/Luhn'sAlgorithm/README.md
Labels: Great Work !, Hacktoberfest, changes-requested, hacktoberfest-accepted

#184 IsStrongPassword.java
  Programming/Java/IsStrongPassword/IsStrongPassword.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#179 added the solution for dice throw problem
  Programming/Java/DiceThrowProblem/Dice_Throw_Problem.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#182 Adding Luhn Alogorithm using JavaScript for the issue #178
  Programming/JavaScript/Luhn/luhnAlogorithm.js
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#183 check anagram.c
  Programming/C++/Anagram/anagram.c
Labels: Great Work !, Hacktoberfest, changes-requested, hacktoberfest-accepted

#193 Created Topological_Sorting.cpp
  Programming/C++/TopologicalSorting/TopologicalSorting.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#194 added NumberSquare.java
  Programming/Java/NumberSquare/NumberSquare.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#196 add binary tree algorithm
  Programming/Python/BinaryTree/BinaryTree.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#199 Update Fibonacci.cpp
  Programming/C++/Fibonacci/Fibonacci.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#198 ProgramOnTowerOfHanoi
  Programming/C++/TowerOfHanoi/tower_Of_Hanoi.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#197 PRIME_CHECKER
  Programming/C++/IsPrime/CheckthenumberisPrimeOrNot.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#195 Luhn's Algorithm in C++
  Programming/C++/LuhnAlgorithm/luhn's_algorithm.cpp
Labels: Hacktoberfest

#185 Added Luhn's Algorithm in C++.
  Programming/C++/LuhnsAlgorithm/LuhnsAlgorithm.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#203 CircularQueue
  Programming/C++/CircularLinkedList/Circular_Link_List.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#211 Update README.md
  README.md
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#216 Solution for Median of Two Sorted Arrays
  Programming/Java/MedianOfTwoSortedArrays/MedianOfTwoSortedArrays.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#217 Longest Palindromic Substring problem
  Programming/C++/LongestPalindromicSubstring/LongestPalindromicSubstring.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#215 ZigZag Conversion #210
  Programming/JavaScript/Zigzag-Conversion/zigzagConversion.js
Labels: Great Work !, Hacktoberfest, Javascript, changes-requested

#218 Length of longest substring without repeating characters
  Programming/Python/LengthOfLongestSubstring/length_of_longest_substring_without_repeating_characters.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#219 Added Reverse integer method for c#
  Programming/C#/ReverseInteger/ReverseInteger.cs
Labels: C#, Great Work !, Hacktoberfest, hacktoberfest-accepted

#221 commit for Add Two Linked List
  Programming/Java/AddTwoNumbers/AddTwoNumber.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#222 Added Median of Two Sorted Arrays folder with .c file in it
  Programming/C++/Median of Two Sorted Arrays/medianoftwosortedarrays.c
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#224 Added Reverse Integer Program in Python
  Programming/Python/Reverse Integer/reverse_integer.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#225 Adding python solution for AddTwoNumber issue #205
  .gitignore
  Programming/Python/AddTwoNumbers/addTwoNumbers.py
Labels: Great Work !, Hacktoberfest, Python, changes-requested

#226 Add Reverse Integer | C++ (#206)
  Programming/C++/ReverseInteger/reverse_signed_integer.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#227 added largest_palindromic_substring.py
  Programming/Python/LargestPalindromicSubstring/largest_palindromic_substring.py
  Programming/Python/MedianOfTwoSortedArrays/median_of_two_sorted_arrays.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#229 Adding Longest Palindromic Substring code [java]
  Programming/Java/LongestPalindromicSubstring/longest_palindromic_substring.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#230 Added reverse integer program in python
  Programming/Python/Reverse_Integer_python/reverseInt.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#214 Reverse of an integer
  Programming/Python/ReverseofANumber/ReverseofANumber.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#234 Added javascript code to reverse number
  Programming/JavaScript/Reverse-Integer/reverseInteger.js
Labels: Great Work !, Hacktoberfest, Javascript, hacktoberfest-accepted

#236 Added Longest Substring Without Repeating Characters
  Programming/C#/longest_substring/longest substring.cs
Labels: C#, Great Work !, Hacktoberfest, hacktoberfest-accepted

#237 add selection sort js
  Programming/JavaScript/SelectionSort/selectionsort.js
Labels: Great Work !, Hacktoberfest, Javascript, hacktoberfest-accepted

#238 Added integer to roman method
  Programming/C#/IntegerToRoman/IntegerToRoman.cs
Labels: C#, Great Work !, Hacktoberfest, hacktoberfest-accepted

#241 Added C program for converting Integer to Roman
  Programming/C++/Integer_to_Roman/integer_to_roman.c
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#240 Python implementation of "Containers with most water"
  Programming/Python/ContainerWithMostWater/container.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#242 Update README.md
  README.md
Labels: Hacktoberfest, documentation, hacktoberfest-accepted

#244 Reverse Integer #206
  Programming/Python/Reverse Integer.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#245 Added Sum of Digits C++ Program
  Programming/C++/SumOfDigits/SumOfDigits.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#246 Added a JAVA code for Container With Most Water
  Programming/Java/container_with_most_water/ContainerWithMostWater.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#247 Addition of digits of a given number - JavaScript solution #235
  Programming/JavaScript/DigitAddition/digitAddition.js
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#248 Easier to understand code
  Programming/C++/CircularLinkedList/LinkedListCircular.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#250 Java Program which add the digits of a Number
  Programming/Java/AddDigitsOfNumber/AddDigitsOfNumber.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#251 [Question] rotate array left k times and right k times. #243 SOLUTION Java
  Programming/Java/RotateKLeftKRight/RotateKLeftKRight.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#252 ReverseInteger.java
  Programming/Java/ReverseInteger/ReverseInteger.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#253 Added Code to find DistanceBetweenBusStops in Java
  Programming/Java/DistanceBetweenBusStops/DistanceBetweenBusStops.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#255 Added Sum of Digits - Python
  Programming/Python/SumOfDigits/SumOfDigits.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#256 Algorithm added for sum of digits of a given number
  Programming/JavaScript/DigitsAddition/DigitsAddition.js
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#257 Rotate array k times in Python
  Programming/Python/RotateArrayKTimes/rotate_array.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#263 Added Java Solution : Rotate Array left and right by k times . (Issue #243)
  Programming/Java/RotatedArray/RotateArrayKtimes.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#264 Added my own issue for checking for even or odd in java
  Programming/Java/EvenOrOdd/EvenOrOdd.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#265 Added Swap Program Without using Temp Variable
  Programming/Python/LinkedList/LinkedList.py
  Programming/Python/SwapNumber/SwapNumber.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#266 Added Python3 code for Regular Expression Matching
  Programming/Python/RegularExpressionMatching/regularExpressionMatching.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#268 The Zoo project
  Programming/Java/Zoo/Animal.java
  Programming/Java/Zoo/Driver.java
  Programming/Java/Zoo/Zoo.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#273 changed incorrect file names and added one program for finding primeN…
  Programming/Java/AnagramsOrNot/AnagramsOrNot.java
  Programming/Java/CheckPrime/CheckPrime.java
  Programming/Java/CheckPrime/PrimeNumbers.java
  Programming/Java/IsStrongPassword/IsStrongPassword.java
  Programming/Java/Iterator/Iterator.java
  Programming/Java/PalindromeOrNot/PalindromeOrNot.java
  Programming/Java/TemperatureConversion/CelciusToFarenheit.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted, refactor

#279 Added LeibnizFormula in C++
  Programming/C++/LeibnizFormula/LeibnizFormula.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#274 Create a Zoo with animals #267
  Programming/Java/Zoo/Animal.java
  Programming/Java/Zoo/Readme.md
  Programming/Java/Zoo/Zoo.java
  Programming/Java/Zoo/ZooKeeper.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#282 Adding ShowShape.java
  Programming/Java/ShowShape/ShowShape.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#284 Add solution to Leibniz Formula in Java
  Programming/Java/LeibnizFormula/LeibnizFormula.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#285 Add solution to Leibniz Formula in Python
  Programming/Python/LeibnizFormula/leibniz_formula.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#286 INTEGER TO ROMAN NUMERALS
  Programming/C++/Integer_to_Roman/INTEGER_TO_ROMAN.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#287 Create MatrixOperations.java
  Programming/Java/MatrixOperations/MatrixOperations.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#280 Added Counting occurrence of each word (Python) #276
  Programming/Python/CountingOccurrenceOfEachWord/CountingOccurrenceOfEachWord.py
  Programming/Python/ModifiedKaprekarNumber/ModifiedKaprekarNumber.py
  Programming/Python/ReverseDoublyLinkedList/ReverseDoublyLinkedList.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#291 Roman_To_Integer.cpp
  Programming/C++/Roman_To_Integer/Roman_To_Integer.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#293 Added RomanToInteger.py
  Programming/Python/DoublyLinkedList/DoublyLinkedList.py
  Programming/Python/RomanToInteger/RomanToInteger.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#294 Added KaperkerNumbers.py
  Programming/Python/KaperkerNumbers/KaperkerNumbers.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#295 Implementation of Luhn's Algorithm in Python based on Java code and Updated it's README.md
  Programming/Java/Luhn'sAlgorithm/README.md
  Programming/Python/LuhnAlgorithm/luhnAlgo.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#296 Added Leibniz'sFormulaForCalculatingPi.py
  Programming/Python/Leibniz'sFormulaForCalculatingPi/Leibniz'sFormulaForCalculatingPi.py
  Programming/Python/LeibnizFormula/leibniz_formula.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted
