Repository aditya109/git-osp-for-beginners, pull requests merged in 2020-11, with the labels that each got.

#311 Updated the indentation error fix
  Programming/Python/AdditonOfDigitsOfAGivenNumber/AdditonOfDigitsOfAGivenNumber.py
  Programming/Python/CannyEdgeDetection/CannyEdgeDetection.py
Labels: Great Work !, Hacktoberfest, Python, bug, hacktoberfest-accepted

#316 Maximum_Gap.cpp
  Programming/C++/Maximum_Gap/Maximum_Gap.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#392 added counter of number of valid triangle triplets in array
  Programming/Python/TriangleTripletsCounter/TriangleTripletsCounter.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#391 Counter of number of valid triangle triplets in array
  Programming/Java/TriangleTripletsCounter/TriangleTripletsCounter.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#389 Longest palindromic subsequence - shorter solution
  Programming/Java/LongestPalindromicSubstring/LongestPalindromicSubstring.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#388 Rearrange an array with O(1) extra space
  Programming/C++/RearrangeArrayO(1)ExtraSpace/RearrangeArrayO(1)ExtraSpace.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#386 Missing element
  Programming/C++/DecimalToBinary/decimaltobinary.cpp
  Programming/C++/Kadanes/kadane.cpp
  Programming/C++/MissingElement/ME.cpp
  Programming/C++/Palindrome/palindrome.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#381 added TwoSum in JavaScript
  Programming/JavaScript/TwoSum/TwoSum.js
Labels: Great Work !, Hacktoberfest, Javascript, hacktoberfest-accepted

#380 added Kadanes Algorithm in JavaScript
  Programming/JavaScript/Kadanes-Algorithm/KadanesAlgorithm.js
Labels: Great Work !, Hacktoberfest, Javascript, hacktoberfest-accepted

#379 Create Pallindrome.cs
  Programming/C#/Pallindrome/Pallindrome.cs
Labels: C#, Great Work !, Hacktoberfest, hacktoberfest-accepted

#378 Create TwoSum.py
  Programming/Python/TwoSum/TwoSum.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#374 Added MaximumGap for C#
  Programming/C#/CheckForPalindrome/Palindrome.cs
  Programming/C#/MaximumGap/MaximumGap.cs
Labels: C#, Great Work !, Hacktoberfest, hacktoberfest-accepted

#373 Solved: Shuffle Array
  Programming/Java/Suffle Array/ShuffleArray.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#370 fibonacci.cpp
  fibonacci.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#360 Java Add Two Numbers
  Programming/Java/CheckPrime/CheckPrime.java
  Programming/Java/CheckPrime/PrimeNumbers.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#358 Inheritance Explanation
  Programming/Java/Inheritance/Inher.java
Labels: Great Work !, Hacktoberfest, Java, changes-requested, hacktoberfest-accepted

#314 Added a Integer to Roman program in JAVA
  Programming/Java/Integer to Roman/IntegertoRoman.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#315 Added FizzBuzz method in Java
  Programming/Java/FizzBuzz/FizzBuzz.java
Labels: Great Work !, Hacktoberfest, Java, hacktoberfest-accepted

#325 Added maximum gap in a adjacent element in sorted array program in JavaScript
  Programming/JavaScript/MaximumGap/Maximumgap.js
Labels: Great Work !, Hacktoberfest, Javascript, hacktoberfest-accepted

#326 Added solution to maximum gap in python
  Programming/Python/Maximum Gap/maximumGap.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#328 Corrected CONTRIBUTING.md to link active issues of this repo
  CONTRIBUTING.md
  Programming/C++/Queue/SortedQueueCheck.cpp
Labels: C/C++, Great Work !, Hacktoberfest, documentation, hacktoberfest-accepted

#329 Moved C source files to separate directory
  Programming/C++/Anagram/Anagram.cpp
  Programming/C/Anagram/anagram.c
  Programming/C/Integer_To_Roman/integer_to_roman.c
  Programming/C/LeibnizFormula/LeibnizFormula.c
  Programming/C/Median of Two Sorted Arrays/medianoftwosortedarrays.c
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted, refactor

#330 Better formatting and typo fix
  Programming/C++/ActivitySelection/ActivitySelection.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted, refactor

#331 Better formatting
  Programming/C++/BalanceStrings/BalanceStrings.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#332 Better loop and switch formatting
  Programming/C++/CircularLinkedList/Circular_Link_List.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted, refactor

#333 More readable formatting
  Programming/C++/CircularLinkedList/LinkedListCircular.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted, refactor

#334 New python example added
  Programming/Python/anypalindrome/anypalindrome.py
Labels: Great Work !, Hacktoberfest, Python, hacktoberfest-accepted

#335 Maximum gap solution in Javascript.
  Programming/JavaScript/Maximum-Gap/MaximumGap.js
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#342 Added code for Longest Substring Without Repeating Characters in c++
  Programming/C++/LongestSubstringWithoutRepeatingCharacters./LongestSubstringWithoutRepeatingCharacters.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#343 Roman to integer
  Programming/Python/RomanToInteger/roman_to_integer.py
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#344 Issue #309 Maximum Gap in Cpp
  Programming/C++/Maximum_Gap/MaximumGap.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#347 Added longest substring without repeating characters(c++)
  Programming/C++/LongestSub_str_without_rep_seq/Longestsubstr.cpp
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#364 Added isPallindrome.cpp file in C++ folder
  Programming/C++/isPallindrome/isPallindrome.cpp
Labels: C/C++, Great Work !, Hacktoberfest, hacktoberfest-accepted

#354 Create Armstrong number
  Programming/C++/Armstrong number
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted

#348 Add Dutch National Flag in Java. Signed-off-by: Thanh Tien Phat Nguyen <ttpnguyen2@myseneca.ca>
  Programming/Java/DutchNationalFlag/DutchNationalFlag.java
Labels: Great Work !, Hacktoberfest, hacktoberfest-accepted
