Repository aditya109/git-osp-for-beginners, pull requests merged in 2021-10, with the labels that each got.

#402 adding issue templates;
  .github/ISSUE_TEMPLATE/python-question
  .github/ISSUE_TEMPLATE/question-expecting-c#-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-c++-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-c-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-golang-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-java-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-javascript-solution.md
Labels: bug, documentation, changes-requested

#405 Add issue templates
  .github/ISSUE_TEMPLATE/question-expecting-c#-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-c++-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-c-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-java-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-javascript-solution.md
Labels: bug, documentation, Hacktoberfest, hacktoberfest-accepted

#412 Update question-expecting-golang-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-golang-solution.md
Labels: bug, documentation, Hacktoberfest, hacktoberfest-accepted

#417 Update question-expecting-python-solution.md
  .github/ISSUE_TEMPLATE/question-expecting-python-solution.md
Labels: bug, documentation, Hacktoberfest, hacktoberfest-accepted

#432 Update README.md
  README.md
Labels: bug, documentation, Hacktoberfest, hacktoberfest-accepted

#436 Solved issue #431 'Combination Sum' raised by aditya109
  Programming/Python/CombinationSum/combinationSum.py
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#482 Merge Sorted Arrray C++
  Programming/C++/MergeSortedArray/MergeSortedArrays.cpp
Labels: good first issue, Golang, Great Work !

#483 TwoSum
  Programming/Kotlin/TwoSum/TwoSum.kt
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#442 Solution for 22. Generate Parentheses
  Programming/C#/Combination Sum/readme.md
  Programming/C#/Combination Sum/solution.cs
  Programming/C#/Generate Parentheses/readme.md
  Programming/C#/Generate Parentheses/solution.cs
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#434 Added Letter Combinations of a Phone
  Programming/Python/LetterCombinationsOfAPhoneNumber/LetterCombinationsOfAPhoneNumber.py
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#444 Added JavaScript Solution for Container With Most Water Problem
  Programming/JavaScript/ContainerWithMostWater/containerWithMostWater.js
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#485 Create golang solution for TwoSum problem
  Programming/Golang/TwoSum/TwoSum.go
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#438 C++ Solution for Container With Most Water Problem
  Programming/C++/ContainerWithMostWater/container_with_most_water_solution_cpp.cpp
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#487 Adding code for Palindrome_Number.
  .vscode/settings.json
  Programming/C++/Palindrome_Number/Palindromenumber.cpp
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#473 Added palindrome checker in java
  Programming/Java/PalindromeOrNot/PalindromeCheck.java
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#495 Generate Parenthesis Code C++
  Programming/C++/Generate Parenthesis/Generate Parenthesis.cpp
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#496 Two Sum Solved
  Programming/C++/Two Sum/Two_Sum.cpp
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#497 Remove Duplicates From Sorted Array in Java!
  Programming/Java/RemoveDuplicates/removeduplicates.java
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#498 Created solution for merge sorted array issue#451
  Programming/Python/MergeSortedArray/merge_sorted_array.py
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted

#500 added code for checking duplicate in a sorted array
  Programming/C++/Checking_duplicate_in_a_sorted _array/Remove_Duplicates_from_Sorted_Array.cpp
Labels: Hacktoberfest, changes-requested

#501 Remove Duplicates From Sorted Array
  Programming/Java/RemoveDuplicatesFromSortedArray/RemoveDuplicatesFromSortedArray.java
Labels: Hacktoberfest, Great Work !, hacktoberfest-accepted
